/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GenerateCSV;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class Main {

	static Logger logger = LoggerFactory.getLogger(Main.class);
	
    public static void main(String[] args) {

    	logger.debug("Main start!!");
    	Main service = new Main();
    	List<MetaBean> mlist = service.getInputFile("InputMetadata.txt");
    	service.write(mlist, "Test.txt");
    	logger.debug("Main end!!");
    }
    
    private List<MetaBean> getInputFile(String path) {
    	
    	Path p = Paths.get(path);
    	List<MetaBean> mlist = new ArrayList<MetaBean>();
    	try {
			Files.lines(p).forEach((item) -> mlist.add(new MetaBean(item)));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	return mlist;
    }
    
    private void write(List<MetaBean> mlist, String path) {
    
        try {
            File file = new File(path);
            // 書き込み権限の確認
    	    if (!file.canWrite()) {
    	        // 書き込み可能に変更
    	        file.setWritable(true);
    	    }
            FileWriter filewriter = new FileWriter(path,true);
            BufferedWriter bw = new BufferedWriter(new FileWriter(file));
            
            List<String> tlist = mlist.stream().map(item -> item.getLabel()).collect(Collectors.toList());
            bw.write(String.join(",", tlist));
            bw.newLine();
            
            for (int i = 0; i < 100; i++) {
            	List<String> vlist = mlist.stream().map(item -> item.getValue()).collect(Collectors.toList());
            	bw.write(String.join(",", vlist));
            	bw.newLine();
            }
            
            bw.close();
         
            logger.debug("CSV File has been created");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public String getString() {
    	return "";
    }
}
