/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GenerateCSV;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Main target = new Main();
        //assertTrue("", target.getString());
    }
}
